csv_app/urls.py
from django.urls import path
from .views import LoginView, SchemaView, LogoutView, SchemaCreateView, SchemaDeleteView, SchemaEditView,\
    SchemaColumnDelete, create_data_sets
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('schema/', login_required(SchemaView.as_view()), name='schemas'),
    path('schema/add/', login_required(SchemaCreateView.as_view()), name='schemas-create'),
    path('schema/edit/<int:pk>', login_required(SchemaEditView.as_view()), name='schema-edit'),
    path('schema/column/delete/<int:pk>/<int:id>', login_required(SchemaColumnDelete.as_view()),
         name='schema-column-delete'),
    path('schema/delete/<int:pk>', login_required(SchemaDeleteView.as_view()), name='schemas-delete'),
    path('schema/dataset/create', login_required(create_data_sets), name='data-sets-generate'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('csv_app.urls')),
]

csv_app/models.py
from django.db import models
from datetime import date


COLUMN_SEPARATOR = (
    (',', 'Comma (,)'),
    (';', 'Dot comma (;)'),
)

STRING_CHARACTER = (
    ('"', 'Double-quote (")'),
    ("'", "Single quote (')"),
)


class Schema(models.Model):
    title = models.CharField(max_length=500, unique=True, verbose_name='Title')
    modified = models.DateField(default=date.today(), verbose_name='Modified')
    column_separator = models.CharField(max_length=500, choices=COLUMN_SEPARATOR, default=',',
                                        verbose_name='Column separator')
    string_character = models.CharField(max_length=500, choices=STRING_CHARACTER, default='"',
                                        verbose_name='String character')


COLUMN_TYPE = (
    ('str', 'String'),
    ('int', 'Integer'),
    ('bool', 'Boolean'),
)


class SchemaColumn(models.Model):
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, verbose_name='Column name')
    type = models.CharField(max_length=500, choices=COLUMN_TYPE, default='str', verbose_name='Type')
    type_info1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='From')
    type_info2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='To')
    order = models.IntegerField(verbose_name='Order')

csv_app/views.py
import csv
import os

from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .helpers import saving_schema_columns, str_generate, int_generate, boolean_generate
from .models import Schema, SchemaColumn


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('schemas')
        return render(request, 'login.html')

    def post(self, request):
        user = authenticate(username=request.POST.get('login'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            return redirect('schemas')
        context = {
            'error': 'Username or password is incorrect',
        }
        return render(request, 'login.html', context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('login')


class SchemaView(ListView):
    model = Schema
    template_name = 'index.html'


class SchemaDeleteView(DeleteView):
    model = Schema
    success_url = reverse_lazy('schemas')


class SchemaCreateView(CreateView):
    model = Schema
    fields = ['title', 'column_separator', 'string_character']
    template_name = 'add_schema.html'
    success_url = reverse_lazy('schemas')

    def form_valid(self, form):
        form_ = super().form_valid(form)
        saving_schema_columns(form, self)
        return form_


class SchemaEditView(UpdateView):
    model = Schema
    fields = ['title', 'column_separator', 'string_character']
    template_name = 'edit_schema.html'
    success_url = reverse_lazy('schemas')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        schema_columns = SchemaColumn.objects.filter(schema_id=self.kwargs['pk'])
        context['id'] = self.kwargs['pk']
        context['schema_columns'] = schema_columns
        return context

    def form_valid(self, form):
        form_ = super().form_valid(form)
        saving_schema_columns(form_, self)
        return form_


class SchemaColumnDelete(DeleteView):
    model = SchemaColumn

    def get_success_url(self):
        id_ = self.kwargs['id']
        return reverse_lazy('schema-edit', kwargs={'pk': id_})

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


def create_data_sets(request):
    schema = Schema.objects.get(id=request.POST.get('schema_id'))
    schema_column = SchemaColumn.objects.filter(schema_id=request.POST.get('schema_id')).order_by('order')
    title = schema.title
    file_name = os.path.join(settings.MEDIA_ROOT, f"{title}.csv")
    with open(file_name, 'w') as f:
        f.write('\n')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename={title}.csv'
    writer = csv.writer(response)
    header_list = []
    header_list_str = ''
    for i in schema_column:
        header_list.append(i.name)
        header_list_str += i.name
        header_list_str += schema.column_separator
    writer.writerow(header_list)
    with open(file_name, 'a') as f:
        f.write(header_list_str)
        f.write('\n')
    row_to_write = []
    str_to_write = ""
    for i in range(1, int(request.POST.get('data_rows')) + 1):
        for j in schema_column:
            if j.type == 'String':
                row_to_write.append(str_generate(schema.string_character))
            elif j.type == 'Boolean':
                row_to_write.append(boolean_generate())
            else:
                try:
                    row_to_write.append(int_generate(int(j.type_info1), int(j.type_info2)))
                except:
                    row_to_write.append(int_generate(0, 100))
        for g in row_to_write:
            str_to_write += g
            str_to_write += str(schema.column_separator)
        writer.writerow([str_to_write])
        with open(file_name, 'a') as f:
            f.write(str_to_write)
            f.write('\n')
        str_to_write = ''
        row_to_write.clear()
    return response

csv_app/templates/add_schema.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
{% endblock %}

{% block body %}
    <div class="container">
    <div class="row mb-3">
        <div class="col-md-3">
            <h3>New schemas</h3>
        </div>
        <div class="col-md-3 ml-auto">
            <button form="new_schema_form" type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
        <div class="row">
            <div class="col-md-4">
                <form method="POST" id="new_schema_form">
                    {% csrf_token %}
                    {{ form|crispy }}
{#                </form>#}
                    <div id="form_hidden_input">
                    </div>
                </form>
            </div>
        </div>
{#        <form method="POST" id="new_schema_form">#}
{#            {% csrf_token %}#}
            <div class="row mt-3">
                <div class="col-md-12">
                    <h3>Schema columns</h3>
                </div>
                    <div id="column_form" class="column_form w-100">
                    </div>

                <div class="row border my-5 w-100">
                    <div class="col-md-3">
                        <label for="col-name">Column name</label>
                        <input class="form-control" type="text" id="col-name">
                    </div>
                    <div class="col-md-3">
                        <label for="col-type">Type</label>
                        <select class="form-control" id="col-type">
                            <option value="str">String</option>
                            <option value="int">Integer</option>
                            <option value="bool">Boolean</option>
                        </select>
                        <p class="text-secondary d-none show_range">
                            <a href="#" class="range_btn">add range ?</a>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <div class="range_add_div d-none">
                            <label for="range_from__">From</label>
                            <input class="form-control w-25" type="number" min="1" id="range_from">
                            <label for="range_to__">To</label>
                            <input class="form-control w-25" type="number" min="1" id="range_to">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <label for="col-order">Order</label>
                        <input class="form-control" type="number" min="1" id="col-order">
                    </div>
                    <div class="col-md-12">
                        <p class="text-danger d-none add_column_error_show">Please fill in all fields</p>
                        <button class="btn btn-primary my-3 column_add_btn">Add column</button>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function(){
            $('#col-type').on('change', function(){
                if($(this).val() === 'int') {
                    $('.show_range').removeClass('d-none')
                } else {
                    $('.show_range').addClass('d-none')
                    $('.range_add_div').addClass('d-none')
                }
            })

            $('.range_btn').on('click', function(){
                $('.range_add_div').toggleClass('d-none')
            })

            $('.column_add_btn').on('click', function(){

                let name = $('#col-name').val();
                let type = $('#col-type').val();
                let order = $('#col-order').val()
                let type_html = document.getElementById('col-type')
                let type_str = type_html.options[type_html.selectedIndex].text;
                let range_from = $('#range_from').val();
                let range_to = $('#range_to').val();

                if(name === '' || type === '' || order === '') {
                    $('.add_column_error_show').removeClass('d-none')
                } else {
                    $('.add_column_error_show').addClass('d-none')
                    let template = `
                    <div class="row align-items-center">
                        <div class="col-md-3">
                            <label>Column name</label>
                            <input name="column_name" class="form-control" type="text" value="${name}" readonly>
                        </div>
                        <div class="col-md-3">
                            <label>Type</label>
                            <input name="column_type" class="form-control" type="text" min="1" value="${type_str}" readonly>
                        </div>
                        <div class="col-md-2 mt-4">
                            <div class="range_add_div d-flex align-items-end">
                                <label>From</label>
                                <input name="column_type_from" class="form-control" type="number" value="${range_from}" readonly>
                                <label>To</label>
                                <input name="column_type_to" class="form-control" type="number" value="${range_to}" readonly>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label>Order</label>
                            <input name="column_order" class="form-control" type="number" min="1" value="${order}" readonly>
                        </div>
                        <div class="col-md-1">
                            <button type="button" onclick="btn_click_add_column(this)" class="btn btn-sm btn-outline-danger">delete</button>
                        </div>
                    </div>
                    `;
                    let hidden_input = `
                        <input name="column_name" type="hidden" value="${name}">
                        <input name="column_type" type="hidden" min="1" value="${type_str}">
                        <input name="column_type_from" type="hidden" value="${range_from}">
                        <input name="column_type_to" type="hidden" value="${range_to}" >
                        <input name="column_order" type="hidden" value="${order}">
                    `
                    document.getElementById('form_hidden_input').innerHTML += hidden_input
                    document.getElementById('column_form').innerHTML += template
                }
            })
        })

        function btn_click_add_column(e) {
            e.parentElement.parentElement.remove()
        }
    </script>
{% endblock %}

csv_app/templates/edit_schema.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}
{% endblock %}

{% block body %}
    <div class="container">
    <div class="row mb-3">
        <div class="col-md-3">
            <h3>Edit schema</h3>
        </div>
        <div class="col-md-3 ml-auto">
            <button type="button" class="btn btn-primary" onclick="forms_submit()">Submit</button>
        </div>
    </div>
        <div class="row">
            <div class="col-md-4">
                <form method="POST" name="new_schema_form">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div id="form_hidden_input">
                    </div>
                    <div id="form_hidden_input_2">

                    </div>
                </form>
            </div>
        </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <h3>Schema columns</h3>
                </div>
                    <div id="column_form" class="column_form w-100">
                        {% for i in schema_columns %}
                            <input type="hidden" name="column_id" value="{{ i.pk }}">
                            <div class="row align-items-center">
                                <div class="col-md-3">
                                    <label>Column name</label>
                                    <input name="column_name" class="form-control" type="text" value="{{ i.name }}" disabled>
                                </div>
                                <div class="col-md-3">
                                    <label>Type</label>
                                    <select name="column_type" class="form-control" disabled>
                                        <option value="{{ i.type }}" selected>{{ i.type }}</option>
                                    </select>
                                </div>
                                <div class="col-md-2 mt-4">
                                    {% if i.get_type_display == 'Integer' %}
                                        <div class="div_hide{{ i.pk }} d-block">
                                            <div class="range_add_div d-flex align-items-end">
                                                <label>From</label>
                                                <input name="column_type_from" class="form-control" type="number" value="{{ i.type_info1 }}" disabled>
                                                <label>To</label>
                                                <input name="column_type_to" class="form-control" type="number" value="{{ i.type_info2 }}" disabled>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-md-3">
                                    <label>Order</label>
                                    <input name="column_order" class="form-control" type="number" min="1" value="{{ i.order }}" disabled>
                                </div>
                                <div class="col-md-1">
                                    <a href="{% url 'schema-column-delete' i.pk id%}" type="submit" class="btn btn-sm btn-outline-danger">delete</a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                <div class="row border my-5 w-100">
                    <div class="col-md-3">
                        <label for="col-name">Column name</label>
                        <input class="form-control" type="text" id="col-name">
                    </div>
                    <div class="col-md-3">
                        <label for="col-type">Type</label>
                        <select class="form-control" id="col-type">
                            <option value="str">String</option>
                            <option value="int">Integer</option>
                            <option value="bool">Boolean</option>
                        </select>
                        <p class="text-secondary d-none show_range">
                            <a href="#" class="range_btn">add range ?</a>
                        </p>
                    </div>
                    <div class="col-md-3">
                        <div class="range_add_div d-none">
                            <label for="range_from__">From</label>
                            <input class="form-control w-25" type="number" min="1" id="range_from">
                            <label for="range_to__">To</label>
                            <input class="form-control w-25" type="number" min="1" id="range_to">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <label for="col-order">Order</label>
                        <input class="form-control" type="number" min="1" id="col-order">
                    </div>
                    <div class="col-md-12">
                        <p class="text-danger d-none add_column_error_show">Please fill in all fields</p>
                        <button class="btn btn-primary my-3 column_add_btn">Add column</button>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        function forms_submit() {
            document.forms["new_schema_form"].submit()
        }
        $(document).ready(function(){
            $('#col-type').on('change', function(){
                if($(this).val() === 'int') {
                    $('.show_range').removeClass('d-none')
                } else {
                    $('.show_range').addClass('d-none')
                    $('.range_add_div').addClass('d-none')
                }
            })

            $('.range_btn').on('click', function(){
                $('.range_add_div').toggleClass('d-none')
            })

            $('.column_add_btn').on('click', function(){

                let name = $('#col-name').val();
                let type = $('#col-type').val();
                let order = $('#col-order').val()
                let type_html = document.getElementById('col-type')
                let type_str = type_html.options[type_html.selectedIndex].text;
                let range_from = $('#range_from').val();
                let range_to = $('#range_to').val();

                if(name === '' || type === '' || order === '') {
                    $('.add_column_error_show').removeClass('d-none')
                } else {
                    $('.add_column_error_show').addClass('d-none')
                    let template = `
                    <div class="row align-items-center">
                        <div class="col-md-3">
                            <label>Column name</label>
                            <input name="column_name" class="form-control" type="text" value="${name}" readonly>
                        </div>
                        <div class="col-md-3">
                            <label>Type</label>
                            <input name="column_type" class="form-control" type="text" min="1" value="${type_str}" readonly>
                        </div>
                        <div class="col-md-2 mt-4">
                            <div class="range_add_div d-flex align-items-end">
                                <label>From</label>
                                <input name="column_type_from" class="form-control" type="number" value="${range_from}" readonly>
                                <label>To</label>
                                <input name="column_type_to" class="form-control" type="number" value="${range_to}" readonly>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label>Order</label>
                            <input name="column_order" class="form-control" type="number" min="1" value="${order}" readonly>
                        </div>
                        <div class="col-md-1">
                            <button type="button" onclick="btn_click_add_column(this)" class="btn btn-sm btn-outline-danger">delete</button>
                        </div>
                    </div>
                    `;
                    let hidden_input = `
                        <input name="column_name" type="hidden" value="${name}">
                        <input name="column_type" type="hidden" min="1" value="${type_str}">
                        <input name="column_type_from" type="hidden" value="${range_from}">
                        <input name="column_type_to" type="hidden" value="${range_to}" >
                        <input name="column_order" type="hidden" value="${order}">
                    `
                    document.getElementById('form_hidden_input').innerHTML += hidden_input
                    document.getElementById('column_form').innerHTML += template
                    document.getElementById('range_from').value = ''
                    document.getElementById('range_to').value = ''
                }
            })
        })

        function btn_click_add_column(e) {
            e.parentElement.parentElement.remove()
        }
        {% for i in schema_columns %}
            $('.column_type{{ i.pk }}').on('change', function(){
                if($(this).val() !== 'int') {
                    $('.div_hide{{ i.pk }}').removeClass('d-block')
                    $('.div_hide{{ i.pk }}').addClass('d-none')
                } else {
                    $('.div_hide{{ i.pk }}').removeClass('d-none')
                    $('.div_hide{{ i.pk }}').addClass('d-block')
                }
            })
        {% endfor %}
    </script>
{% endblock %}

csv_app/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block css %} {% endblock %}

{% block body %}
    <div class="container">
    <div class="row mb-3">
        <div class="col-md-3">
            <h3>Data schemas</h3>
        </div>
        <div class="col-md-3 ml-auto">
            <a href="{% url 'schemas-create' %}" class="btn btn-success">New schema</a>
        </div>
    </div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Modified</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
          {% for i in object_list %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ i.title }}</td>
              <td>{{ i.modified }}</td>
              <td class="d-flex">
                  <a href="{% url 'schema-edit' i.pk %}" class="btn btn-sm btn-outline-primary mx-3">Edit schema</a>
                  <form method="POST" action="{% url 'schemas-delete' i.pk %}">
                      {% csrf_token %}
                      <input type="hidden" value="DELETE">
                      <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                  </form>
                  <a href="#exampleModal" data-schema-id="{{ i.pk }}" type="button" class="btn btn-sm btn-outline-secondary mx-3" data-toggle="modal" data-target="#exampleModal">
                      Generate data
                    </a>
              </td>
            </tr>
              {% empty %}
              <tr>
                <td colspan="4" class="text-center table-secondary">Empty</td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
    </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <label>Enter number of rows</label>
          <form id="row_form" method="POST" action="{% url 'data-sets-generate' %}">
              {% csrf_token %}
                <input type="number" min="1" name="data_rows" class="form-control">
                <input id="schema_id" type="hidden" name="schema_id">
          </form>
      </div>
      <div class="modal-footer">
        <button id="model_close_btn" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button onclick="document.getElementById('model_close_btn').click()" form="row_form" type="submit" class="btn btn-primary">Generate and download</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
    <script>
        $('#exampleModal').on('show.bs.modal', function (e) {
            document.getElementById('schema_id').value = $(e.relatedTarget).attr('data-schema-id')
        })
    </script>
{% endblock %}

csv_app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>FakeCSV</title>
    <link rel="stylesheet" href="{% static 'css/boostrap/css/bootstrap.min.css' %}">
    <style>
        a:hover {
            text-decoration: none;
        }
    </style>
    {% block css %}
    {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <div class="container">
      <a class="navbar-brand" href="#"><b>FakeCSV</b></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'schemas' %}">Schemas</a>
          </li>
        </ul>
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <span class="nav-link">
                Hello <b>{{ request.user }}</b>
            </span>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
      </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
</body>

<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}

</html>

csv_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>FakeCSV Login</title>
    <link rel="stylesheet" href="{% static 'css/boostrap/css/bootstrap.min.css' %}">
    <style>
        .login_card {
            margin-top: 30vh;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card login_card text-center bg-light p-5">
                    <h3>Login</h3>
                    <div class="row">
                        <form class="mx-auto" method="POST" action="{% url 'login' %}">
                            {% csrf_token %}
                            <div class="col-md-12">
                                <input class="form-control my-3" type="text" required name="login" placeholder="username">
                            </div>
                            <div class="col-md-12">
                                <input class="form-control my-3" type="password" required name="password" placeholder="password">
                                <p class="text-danger">{{ error }}</p>
                            </div>
                            <div class="col-md-12 text-right">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="{% static 'js/bootstrap/js/bootstrap.min.js' %}"></script>
</html>